// <auto-generated />
namespace sushi_site_work.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mb));
        
        string IMigrationMetadata.Id
        {
            get { return "202011170016070_mb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
